language: node_js
node_js: stable

# macOS 10.14
os: osx
osx_image: xcode10.2

# 'chrome: stable' addon is not necessary since puppeteer package installs Chrome
# on `npm install`
addons:
  homebrew:
    packages:
      - emscripten
      - binaryen
    update: true

env:
  - LLVM=/usr/local/opt/emscripten/libexec/llvm/bin EMSCRIPTEN=/usr/local/opt/emscripten/libexec

# `emcc --version` is important since emcc does not work on first command execution
# Run `emcc hi.c` to generate libc bitcode  at ~/.emscripten_cache/
# and binaryen cache at ~/.emscripten_port before running `emconfigure ./configure`
before_script:
  - brew info binaryen emscripten
  - emcc --version
  - emcc --version
  - mkdir emcc_sanity && cd ./emcc_sanity
  - echo 'int main() { return 0; }' > hi.c
  - emcc hi.c
  - cd -

script:
  - echo -e "\\033[33;1mBuilding Normal Vim\\033[0m" && echo -en "travis_fold:start:BUILD_NORMAL\\r\\033[0K"
  - ./build.sh
  - echo -en "travis_fold:end:BUILD_NORMAL\\r\\033[0K"
  - cd ./wasm
  - echo -e "\\033[33;1mRunning Tests\\033[0m" && echo -en "travis_fold:start:TEST\\r\\033[0K"
  - "npm test -- --travisci | tee log.txt | grep -v 'LOG: '"
  - echo -en "travis_fold:end:TEST\\r\\033[0K"
  - cd -
  - echo -e "\\033[33;1mBuilding Small Vim\\033[0m" && echo -en "travis_fold:start:BUILD_SMALL\\r\\033[0K"
  - make clean && VIM_FEATURE=small ./build.sh configure make emcc
  - echo -en "travis_fold:end:BUILD_SMALL\\r\\033[0K"

after_failure:
  - if [ -f ./wasm/log.txt ]; then cat ./wasm/log.txt; fi
  - if [ -f ./log.txt ]; then cat ./log.txt; fi
  - if [ -f ./src/config.log ]; then cat ./src/config.log; fi

before_cache:
  - brew cleanup

cache:
  npm: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.emscripten_cache
    - $HOME/.emscripten_ports

branches:
  except:
    - upstream
    - /^v[0-9]/

# vim:set sts=2 sw=2 tw=0 et:
