language: node_js
node_js: stable

# macOS 10.14
os: osx
osx_image: xcode11.3

# Note: 'chrome: stable' addon is not necessary since puppeteer package installs
# Chrome on `npm install`

before_script:
  - |
    git clone --depth 1 --single-branch https://github.com/emscripten-core/emsdk.git
    cd emsdk
    ./emsdk install latest
    ./emsdk activate latest
    source ./emsdk_env.sh
    cd ..
  - node --version
  - emcc --version

script:
  - echo -e "\\033[33;1mBuilding Normal Vim\\033[0m" && echo -en "travis_fold:start:BUILD_NORMAL\\r\\033[0K"
  - ./build.sh
  - echo -en "travis_fold:end:BUILD_NORMAL\\r\\033[0K"
  - cd ./wasm
  - echo -e "\\033[33;1mRunning Tests\\033[0m" && echo -en "travis_fold:start:TEST\\r\\033[0K"
  - "npm test -- --travisci | tee log.txt | grep -v 'LOG: '"
  - echo -en "travis_fold:end:TEST\\r\\033[0K"
  - cd -
  - echo -e "\\033[33;1mBuilding Small Vim\\033[0m" && echo -en "travis_fold:start:BUILD_SMALL\\r\\033[0K"
  - make clean && VIM_FEATURE=small ./build.sh configure make emcc
  - echo -en "travis_fold:end:BUILD_SMALL\\r\\033[0K"

after_failure:
  - if [ -f ./wasm/log.txt ]; then cat ./wasm/log.txt; fi
  - if [ -f ./log.txt ]; then cat ./log.txt; fi
  - if [ -f ./src/config.log ]; then cat ./src/config.log; fi

cache:
  npm: true

branches:
  except:
    - upstream
    - /^wasm-[0-9]+\.[0-9]+\.[0-9]+$/

# vim:set sts=2 sw=2 tw=0 et:
