language: node_js
node_js: stable

# macOS 10.14
os: osx
osx_image: xcode10.2

# 'chrome: stable' addon is not necessary since puppeteer package installs Chrome
# on `npm install`
addons:
  homebrew:
    packages:
      - emscripten
      - binaryen
    update: true

env:
  - LLVM=/usr/local/opt/emscripten/libexec/llvm/bin

# `emcc --version` is important since emcc does not work on first command execution
before_script:
  - brew info binaryen emscripten
  - emcc --version

script:
  - ./build.sh
  - cd ./wasm && npm test

before_cache:
  - brew cleanup

cache:
  npm: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.emscripten_cache
    - $HOME/.emscripten_ports

# vim:set sts=2 sw=2 tw=0 et:
