language: node_js
node_js: stable

# macOS 10.14
os: osx
osx_image: xcode10.2

addons:
  homebrew:
    packages:
      - emscripten
      - binaryen
    update: true

env:
  - LLVM=/usr/local/opt/emscripten/libexec/llvm/bin

before_script:
  - brew info binaryen emscripten

script:
  - ./build.sh

# vim:set sts=2 sw=2 tw=0 et:
